### ISSUE TITLE
Crashes once start button pressed

### ISSUE THREAD

**Issue by crushton81** [LePopal/PRACT-OBS#11]
i know this version is slated for Rekordbox 6.0.1 but i t was working with Rekordbox 6.0.2 until my computer PC did the last windows update yesterday. 

After i start Pract OBS and hit the start button its crashes immediately. 

- Rekordbox Ver 6.0.2
- Windows 10 pro 
- last windows update was: this seems like ti would be unrelated but after this update is when it started failing.  
https://support.microsoft.com/en-ca/help/4559309/update-for-the-new-microsoft-edge-for-windows-10-version-1803-to-2004 

here is the error from the event viewer:
 
Faulting application name: PRACT_OBS.exe, version: 0.6.1.0, time stamp: 0x5e9fbf92
Faulting module name: KERNELBASE.dll, version: 10.0.18362.815, time stamp: 0xb89efff3
Exception code: 0xe0434352
Fault offset: 0x000000000003a799
Faulting process id: 0xeac
Faulting application start time: 0x01d6463cec6aed92
Faulting application path: C:\Program Files (x86)\Popal\PRACT OBS\PRACT_OBS.exe
Faulting module path: C:\WINDOWS\System32\KERNELBASE.dll
Report Id: 613827b4-88ba-4659-807b-1359a25c4926
Faulting package full name: 
Faulting package-relative application ID: 

Application: PRACT_OBS.exe
CoreCLR Version: 4.700.20.26901
.NET Core Version: 3.1.5
Description: The process was terminated due to an unhandled exception.
Exception Info: System.InvalidOperationException: The data is NULL at ordinal 5. This method can't be called on NULL values. Check using IsDBNull before calling.
   at Microsoft.Data.Sqlite.SqliteValueReader.GetString(Int32 ordinal)
   at Microsoft.Data.Sqlite.SqliteDataReader.GetString(Int32 ordinal)
   at PRACT_OBS.Classes.Helpers.LastTrackHelper.GetCurrentTracksList()
   at PRACT_OBS.Classes.Helpers.LastTrackHelper.GetLastTrack()
   at PRACT_OBS.MainForm.ContinuousExport()
   at System.Threading.ThreadHelper.ThreadStart_Context(Object state)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location where exception was thrown ---
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.ThreadHelper.ThreadStart()

**Comment by LePopal** [comment]
Can you give me the debug info you can find in the Help menu and send me your master.db file by mail ? dj at popal dot fr
Thanks

**Comment by LePopal** [comment]
I close the issue. It's related to the master.db. Some value is not managed. But without the DB, I can't do anything.

**Comment by dhannyz** [comment]
@LePopal this is also occurring for a friend of mine, I will try to get his debug and master.db

**Comment by LePopal** [comment]
Thx

**Comment by FaithInTheGlitch** [comment]
I'm the person with the same problem that dhannyz was talking about. How do I get the debut and master.db?

**Comment by dhannyz** [comment]
@LePopal reading through the debug above it looks like this is related to the databse query column `c.ImagePath`
When trying to read that column you are not calling `edr.IsDBNull(i)` here
https://github.com/LePopal/PRACT-OBS/blob/c3791ea2357c70f19f26724664decf50c858a819/PRACT_OBS/Classes/Helpers/LastTrackHelper.cs#L47
