### ISSUE TITLE
Crash when clicking "start" when using Rekordbox v6.0.3 released on Wed July 15

### ISSUE THREAD

**Issue by craigspree** [LePopal/PRACT-OBS#12]
**Describe the bug**
After launching Pract OBS and pointing it at the location of the new Rekordbox v6.0.3 exe file, and pressing 'start' when RekordBox is running, Pract OBS will crash and quit. Pract OBS still works with Rekordbox 6.0.2 so I imagine there's an incompatibility with the new version of RekordBox 6.0.3

**To Reproduce**
1. Launch Rekordbox 6.0.3
2. Launch Pract OBS
3. Go into Pract OBS settings and select the location for the Rekordbox 6.0.3 exe file
4. Press "Start" in Pract OBS. After a few seconds, Pract OBS will crash/force quit

**Expected behavior**
Expected behavior is for Pract OBS to work as awesomely as it does for RekordBox 6.0.2

**Desktop (please complete the following information):**
 - OS: Windows 10. 16 GB Ram. Surface Book 2, nothing else running other than Pract OBS and RekordBox 6.0.3

**Additional context**
As another topic, could you please share a Patreon link or your PayPal info so I can donate money to your efforts on Pract OBS? It has become an absolutely essential tool for my live streams. My fans love it, and I want to ensure you are rewarded for your efforts. :)

**Comment by LePopal** [comment]
Please send me your master.db database by email to DJ at popal dot fr.

Le ven. 17 juil. 2020 à 04:32, craigspree <notifications@github.com> a
écrit :

**Comment by LePopal** [comment]
@craigspree be sure to grab the lastest version 0.6.4. Pioneer did make a slight change somewhere.

**Comment by craigspree** [comment]
Thank you so much!
