### ISSUE TITLE
Rekordbox 5 compatibility

### ISSUE THREAD

**Issue by fdebkowski** [LePopal/PRACT-OBS#15]
Hi
Is it possible to make this program work with rekordbox 5?

**Comment by LePopal** [comment]
Hi. It's never going to happen. 

On the one hand, Rekordbox 5 uses a different database engine which make it difficult to query and to reuse the existing code.
On the other hand, Rekordbox 6 is now mature enough (as of v6.2) to not to rely on v5 anymore.
