### ISSUE TITLE
Add an option to only show tracks played after PRACT was started

### ISSUE THREAD

**Issue by eshy** [LePopal/PRACT-OBS#5]
**Is your feature request related to a problem? Please describe.**
When PRACT is started right now, it will display whatever track was last played, even if that was a while ago. 

**Describe the solution you'd like**
The simplest way to solve this is to have a "Clear" button that will just delete the current content. 

Another solution is to ignore any tracks that were played before the app was started and only start updating the text/art files when the first change is detected

I'm creating this as a feature request since it's easy to work around it by simply not displaying the track info when you start streaming and only switching to that scene in OBS once the first track is detected but it would be nice to have

**Comment by LePopal** [comment]
Thanks for your feedback!

Here's what I'll do:

1. Add some routine to filter out the tracks played before the program startup
1. Add a new settings to make it optional
1. Add a routine to clean the physical files and matching options to clean at the program startup or shutdown

**Comment by LePopal** [comment]
Please have a look : https://github.com/LePopal/PRACT-OBS/releases/tag/v0.6-preview

**Comment by LePopal** [comment]
This new feature is available in version [0.6.0](https://github.com/LePopal/PRACT-OBS/releases/tag/v0.6.0)
