### ISSUE TITLE
A couple of suggestions

### ISSUE THREAD

**Issue by NemisisDragon** [LePopal/PRACT-OBS#7]
Hi LePopal,

I would like to make a couple of suggestions for PRACT-OBS:

1. Adding export for LABEL information. The label is stored in rekordbox, it should be easy to read that out.
2. Doing an optional string manipulation for the track title because of the key information. 
For example many tracks are saved like this: Artist - Title (Mix) - 9B - 130
So basically it would be cool to use an regular expression like replace ") -*" with ")".
After that, it would look like that: Artist - Title (Mix)
3. I know you don't want to read this, but PLEASE add support for the stable version 5.x of rekordbox. The majority of DJs use this one. Currently rekordbox 6 is such a mess!

Thanks for your time and reading, it would be cool if you can reply!
Cheers!

**Comment by LePopal** [comment]
Hi !
Thanks for your feedback. I'll try to answer your suggestion the best I can.
1. It's definitely feasable. I'll take note for later
2. In my collection I have no tracks with a title like "Title (Mix) - 9B - 130". Those infos are stored in separate fields. Field transform is maybe a feature I may add in the future but not for now. It would be very time consuming for me :-( 
3. I honestly can't add support to Rekordbox 5.x. Hopefully an Open Source developer can help me on this matter.

**Comment by LePopal** [comment]
And I'd like to add that I consider RB6 messy as well: I reverted back to 5.8.5 for my main usage :'(

**Comment by LePopal** [comment]
The Label is already there : select %LABEL% for the custom export format
